<?php

/**
 * @file
 * They Said So Module.
 */

/**
 * Implements hook_theme().
 */
function quote_theme($existing, $type, $theme, $path) {
  return [
    'quote' => [
      'variables' => [
        'cite' => NULL,
        'author' => NULL,
        'quote' => NULL,
        'title' => NULL,
        'attribution' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function quote_preprocess_node__page__full(&$variables) {
  $quote = \Drupal::service('quote.tss')->getQuoteOfTheDay();
  $config = \Drupal::config('quote.settings');
  if (!empty($quote)) {
    $variables['content']['quote'] = [
      '#theme' => 'quote',
      '#cite' => $quote['permalink'],
      '#author' => $quote['author'],
      '#quote' => $quote['quote'],
      '#title' => $quote['title'],
      '#attribution' => isset($config->attribution) ? $config->attribution : TRUE,
      '#weight' => 1000,
    ];
  }
}
